// <auto-generated />
using System;
using Authorization.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Authorization.EF.Migrations
{
    [DbContext(typeof(AuthorizationDbContext))]
    [Migration("20230224131519_AddUserActionNotificationSettings")]
    partial class AddUserActionNotificationSettings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Authorization.Domain.Settings.SettingsEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("SettingsEntryId");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SettingsEntries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "UserActionNotifications:ReceiversEmails",
                            Description = "Receivers emails can be list of emails divided by ';'."
                        },
                        new
                        {
                            Id = "UserActionNotifications:IsLoginNotifyEnabled",
                            Description = "Enable send user login email service or not",
                            Value = "False"
                        },
                        new
                        {
                            Id = "UserActionNotifications:UserLoginEmailSubject",
                            Description = "User login email subject",
                            Value = "User logged"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
