INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-application-read')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-application-add')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-application-update')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-application-delete')

INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-user-read')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-user-read-one')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-user-add')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-user-update')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-user-delete')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-user-status-read')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-user-status-suspend')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-user-status-block')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-user-role-read')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-user-role-update')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-user-claim-read')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-user-claim-update')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-user-email-read')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-user-email-update')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-user-email-verify')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-user-phone-read')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-user-phone-verify')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-user-password-update')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-user-password-reset')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-user-unlock')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-employee-read')

INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-role-read')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-role-add')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-role-update')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-role-delete')

INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-claim-read')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-claim-add')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-claim-delete')

INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-profile-password-change')
INSERT [dbo].[Claims] ([ClaimId], [CreateTimeUtc], [UpdateTimeUtc], [Type], [Value]) VALUES (NEWID(), GETUTCDATE(), GETUTCDATE(), N'claim', N'authorization-profile-password-set')


